GET http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZm9vIiwiaWQiOiI2NmNhNzI5NTIyNWJjYTRiMmM4MjZhM2UiLCJpYXQiOjE3MjQ2Mjg2NDAsImV4cCI6MTcyNDYzMjI0MH0.iabBJA8-DIIK4Pgo5sPnAJPfmDS0NzOyjj3ncHIuxII

###

GET http://localhost:3001/api/users