POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYmFyIiwiaWQiOiI2NmI5MmIyODRkMmUxNGI5NDYxOTdjOTUiLCJpYXQiOjE3MjQ1MzA4MTB9.c38i2GOJ4JmaLE5ixUOYzn1T15bCSWTxnzMcrP6_T0s

{
    "title": "new blog created by user",
    "author": "bar baz",
    "url": "example.com",
    "userId": "66b92b284d2e14b946197c95"
}

###

POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "foo",
    "name": "foo bar",
    "password": "123456"
}

###

POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "bar",
    "password": "123456"
}